backend/cpu_backend/urls.py
from django.contrib import admin
from django.views.generic.edit import CreateView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, reverse_lazy

from users.forms import CustomUserCreationForm

urlpatterns = [
    path('', include('cpus.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=CustomUserCreationForm,
            success_url=reverse_lazy('cpus:index'),
        ),
        name='registration',
    ),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Если проект запущен в режиме разработки
if settings.DEBUG:
    import debug_toolbar
    # Добавить к списку urlpatterns список адресов из приложения debug_toolbar:
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

handler404 = 'core.views.page_not_found'

backend/cpus/urls.py
from django.urls import path

from . import views

app_name = 'cpus'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'about/',
        views.About.as_view(),
        name='about'
    ),
    path('cpus_list/', views.cpus_list, name='cpus_list'),
    path('cpu_detail/<int:pk>/', views.cpu_detail, name='cpu_detail'),
    path('user_cpus/<int:pk>/', views.user_cpus, name='user_cpus'),
    path(
        'cpu_add/',
        views.CpuCreateView.as_view(),
        name='cpu_add'
    ),
    path(
        'cpu_detail/<int:pk>/edit/',
        views.CpuUpdateView.as_view(),
        name='cpu_edit',
    ),
    # path(
    #     'cpu_detail/<int:pk>/delete/',
    #     views.cpu_delete,
    #     name='cpu_delete'
    # ),
    path(
        'cpu_detail/<int:pk>/delete/',
        views.CpuDeleteView.as_view(),
        name='cpu_delete'
    ),
]

backend/carousel/models.py
from django.db import models

from cpu_backend.constants import (
    NAME_LONG_NUMBCHAR,
)


class Carousel(models.Model):

    name = models.CharField(
        max_length=NAME_LONG_NUMBCHAR,
        verbose_name='название',
    )
    banner = models.ImageField(
        upload_to='carousel/',
        verbose_name='изображение',
    )

    class Meta:
        verbose_name = 'Баннер'
        verbose_name_plural = 'Баннеры'

    def __str__(self):
        return f'Баннер {self.name}'

backend/cpus/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse

from cpu_backend.constants import (
    NAME_SHORT_NUMBCHAR,
    CHOICE_NUMBCHAR,
)
from cpus.validators import real_date

User = get_user_model()


def user_cpu_directory_path(instance, filename):
    """
    Функция для генерации пути сохранения изображений процессоров.
    Файл будет загружен в MEDIA_ROOT/user_<id>/cpu_<id>/<filename>
    """
    return 'user_{0}/cpu_{1}/{2}'.format(
        instance.cpu.user.id,
        instance.cpu.id,
        filename
    )


class BaseModel(models.Model):
    created_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name='Дата добавления',
    )

    class Meta:
        abstract = True


class Manufacturer(BaseModel):
    """
    Производитель
    """
    name = models.CharField(
        max_length=NAME_SHORT_NUMBCHAR,
        verbose_name='тип',
    )

    class Meta:
        verbose_name = 'производитель'
        verbose_name_plural = 'Производители'

    def __str__(self):
        return self.name


class Cpu(BaseModel):
    """
    Процессор
    """
    NOTEST = 'NT'
    WORK = 'WK'
    DEFECTIVE = 'DF'
    OVERCLOCK = 'OC'
    NONE = 'NN'
    COMMON = 'CM'
    UNOCOMMON = 'UN'
    RARE = 'RR'
    EXTRARARE = 'ER'

    RARITY_CHOICES = [
        (NONE, 'Не задано'),
        (COMMON, 'Частый'),
        (UNOCOMMON, 'Нечастый'),
        (RARE, 'Редкий'),
        (EXTRARARE, 'Очень редкий'),
    ]

    STATUS_CHOICES = [
        (NOTEST, 'Непроверенный'),
        (WORK, 'Рабочий'),
        (DEFECTIVE, 'Неисправен'),
        (OVERCLOCK, 'Разогнан'),
    ]

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='cpus',
        verbose_name='владелец'
    )
    part_number = models.CharField(
        max_length=NAME_SHORT_NUMBCHAR,
        verbose_name='серийный номер',
    )
    catalog_number = models.CharField(
        max_length=4,
        verbose_name='номер в коллекции',
        blank=True
    )

    description = models.TextField(
        blank=True,
        null=True,
        verbose_name='описание'
    )
    hidden_description = models.TextField(
        blank=True,
        null=True,
        verbose_name='Скрытое описание'
    )
    work_status = models.CharField(
        max_length=CHOICE_NUMBCHAR,
        choices=STATUS_CHOICES,
        default=NOTEST,
        verbose_name='статус'
    )
    rarity = models.CharField(
        max_length=CHOICE_NUMBCHAR,
        choices=RARITY_CHOICES,
        default=NONE,
        verbose_name='редкость'
    )
    manufacturer = models.ForeignKey(
        Manufacturer,
        on_delete=models.CASCADE,
        related_name='cpus',
        verbose_name='производитель',
    )
    family = models.CharField(
        max_length=NAME_SHORT_NUMBCHAR,
        verbose_name='семейство',
    )
    frequency = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='частота процессора',
    )
    fsb = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='частота шины',
        blank=True,
        null=True,
    )
    multiplier = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='множитель',
        blank=True,
        null=True,
    )
    fpu = models.BooleanField(
        default=True,
        verbose_name='математический сопроцессор (FPU)'
    )
    l1_cache_size = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='размер кеша L1',
        blank=True,
        null=True,
    )
    vcore = models.FloatField(
        validators=[MinValueValidator(1)],
        verbose_name='напряжение ядра',
        blank=True,
        null=True,
    )

    overclk_frequency = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='частота в разгоне',
        blank=True,
        null=True,
    )
    overclk_fsb = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='частота шины в разгоне',
        blank=True,
        null=True,
    )
    overclk_multiplier = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='множитель в разгоне',
        blank=True,
        null=True,
    )
    overclk_vcore = models.FloatField(
        validators=[MinValueValidator(1)],
        verbose_name='напряжение ядра в разгоне',
        blank=True,
        null=True,
    )

    purchase_date = models.DateField(
        verbose_name='дата покупки',
        validators=(real_date,)
    )
    purchase_price = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='стоимость покупки',
        blank=True,
        null=True,
    )
    sale_price = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='стоимость продажи',
        blank=True,
        null=True,
    )
    sale_date = models.DateField(
        verbose_name='дата продажи',
        blank=True,
        null=True,
        validators=(real_date,)
    )

    is_published = models.BooleanField(
        default=True,
        verbose_name='опубликовано',
        help_text='Снимите галочку, чтобы скрыть публикацию.'
    )
    in_interesting = models.BooleanField(
        default=False,
        verbose_name='В интересном',
        help_text='Снимите галочку, чтобы скрыть с главной.'
    )

    class Meta:
        ordering = ('-purchase_date', '-created_at')
        verbose_name = 'процессор'
        verbose_name_plural = 'Процессоры'
        constraints = (
            models.UniqueConstraint(
                fields=(
                    'catalog_number',
                    'user'
                ),
                name='uniq_cpu'
            ),
        )

    def __str__(self):
        return self.part_number

    def get_absolute_url(self):
        return reverse('cpus:cpu_detail', kwargs={'pk': self.pk})


class ImageCpu(models.Model):
    """
    Изображения для процессора
    """
    name = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        verbose_name='название изображения',
    )
    cpu = models.ForeignKey(
        Cpu,
        on_delete=models.CASCADE,
        related_name='images',
        verbose_name='процессор',
    )
    image = models.ImageField(
        upload_to=user_cpu_directory_path,
        verbose_name='фото процессора',
    )
    default = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        # Проверяем, есть ли уже у этого процессора изображение с default=True
        existing_default_image = ImageCpu.objects.filter(
            cpu=self.cpu,
            default=True
        ).first()
        if existing_default_image and self.default:
            # Если такое изображение существует и default=True,
            # то сбрасываем default на False у существующего изображения
            existing_default_image.default = False
            existing_default_image.save()
        super().save(*args, **kwargs)

backend/templates/includes/carousel.html
{% load static %}
<div class="container-fluid my-carusel">
    <!-- Карусель -->
    <div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-bs-ride="carousel" data-bs-interval="3000">
      <div class="carousel-indicators">

        {% for i in banners %}
          {% if forloop.first %}
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ forloop.counter0 }}" class="active" aria-current="true" aria-label="Слайд {{ forloop.counter0 }}"></button>
          {% else %}
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ forloop.counter0 }}" aria-label="Слайд {{ forloop.counter0 }}"></button>
          {% endif %}
        {% endfor %}

      </div>
      <div class="carousel-inner">
        {% for banner in banners %}
          {% if forloop.first %}
            <div class="carousel-item active">
              <img src="{{ banner.banner.url }}" class="d-block w-100" alt="{{ banner.name }}">
            </div>
          {% else %}
            <div class="carousel-item">
              <img src="{{ banner.banner.url }}" class="d-block w-100" alt="{{ banner.name }}">
            </div>
          {% endif %}
        {% endfor %}

      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>

backend/templates/includes/cpu_card.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<div class="col-xl-4 col-md-6 col-sm-12 mt-4">
  <div class="product-card">
    <div class="product-thumb card">
      <a href="{% url 'cpus:cpu_detail' cpu.id %}">
        {% if cpu.default_image %}
          <img src="{{ cpu.default_image.0.image.url }}"> 
        {% else %}
          <img src="{% static 'img/nocpu.jpg' %}">
        {% endif %}
      </a>
      <div class="card-img-overlay">
        <div class=" d-flex justify-content-between">
          <span class="badge rounded-pill bg-danger text-bg-primary">
            {{ cpu.get_rarity_display }}
          </span>
          <span class="badge rounded-pill bg-success text-bg-primary">
            {{ cpu.get_work_status_display }}
          </span>
      </div>
      </div>
    </div>
    <div class="product-details">
      <div class="product-main-details">
        <h4>
          <a href="{% url 'cpus:cpu_detail' cpu.id %}">
            {{ cpu.part_number }} 
            {% if cpu.month_cpus %}
              <span class="badge bg-secondary text-bg-secondary">Новый</span>
            {% endif %}
          </a>
        </h4>
        <h6>В коллекции</strong> 
          {% if 'cpus:cpus_list' == view_name %}
            <a href="{% url 'cpus:user_cpus' cpu.user.id %}">
            <span class="badge rounded-pill bg-primary text-bg-primary">@{{ cpu.user.username }}</span></a>
          {% endif %}
          с {{ cpu.purchase_date }}</h6>
        <div class="about"><span class="product-list">Производитель:</span> {{ cpu.manufacturer }}</div>
        <div class="about"><span class="product-list">Частота:</span> {{ cpu.frequency }} Мгц</div>
      </div>
      <div class="product-bottom-details d-flex justify-content-between">
        <div class="product-fav">
        </div>
        <div class="product-links">
          <a href="{% url 'cpus:cpu_detail' cpu.id %}"><button type="button" class="btn btn-primary">Подробнее</button></a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endwith %}

backend/templates/includes/footer.html
<!-- footer.html -->
<footer>
  <section class="footer">
    <div class="container">
      <div class="row">

        <div class="col-md-6 col-sm-12">
          <h4>Разделы сайта</h4>
          <ul class="list-unstyled">
            <li><a href="{% url 'cpus:index' %}">Главная</a></li>
            <li><a href="{% url 'cpus:cpus_list' %}">Каталог</a></li>
            <li><a href="{% url 'cpus:about' %}">Контакты</a></li>
          </ul>
        </div>

        <div class="col-md-6 col-sm-12">
          <p class="footer-text">© Mikhail Renzhin, {% now 'Y' %}</p>
        </div>
      </div>
    </div>
  </section>
</footer>

backend/templates/includes/header.html
<!-- header.html -->
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<header>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'cpus:index' %}">
        <img src="{% static 'img/logo.png' %}" alt="Коллекционер 486" width="50" height="50" class="d-inline-block align-text-top">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
  
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 top-menu-my">
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'cpus:index' %}active{% endif %}" href="{% url 'cpus:index' %}">
              Главная
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'cpus:cpus_list' %}active{% endif %}" href="{% url 'cpus:cpus_list' %}">
              Каталог
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'cpus:about' %}active{% endif %}" href="{% url 'cpus:about' %}">
              О проекте
            </a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'cpus:cpu_add' %}active{% endif %}" href="{% url 'cpus:cpu_add' %}">
                Добавить процессор
              </a>
            </li>
          {% endif %}
        </ul>
  
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">
              {% if user.is_authenticated %}
              {{ user }} &nbsp;
              {% endif %}
              <i class="far fa-user"></i></a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% if user.is_authenticated %}
                <li>
                  <a class="dropdown-item" href="{% url 'logout' %}">Выйти</a>
                  <a class="dropdown-item" href="{% url 'password_change' %}">Сменить пароль</a>
                </li>
              {% else %}
                <li>
                  <a class="dropdown-item" href="{% url 'login' %}">Авторизация</a>
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'registration' %}">Регистрация</a>
                </li>
              {% endif %}
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header> 
{% endwith %}

backend/templates/includes/mini_cpu.html
<li><a href="{% url 'cpus:cpu_detail' cpu.id %}">{{ cpu.part_number }}</a> <span class="badge rounded-pill bg-primary text-bg-primary">@{{ cpu.user.username }}</span></li>

backend/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav class="my-5">
    <ul class="pagination">
      <!-- Если существует предыдущая страница 
           (если мы не на первой странице) 
           рисуем кнопку "Первая страница"... -->
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">Первая</a>
        </li>
        <!-- ...и кнопку "Предыдущая" -->
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      <!-- Перебираем в цикле все номера страниц -->
      {% for i in page_obj.paginator.page_range %}
        <!-- Если номер страницы совпадает с i... -->
        {% if page_obj.number == i %}
          <!-- ..."подсвечиваем" кнопку: ставим класс "active"
               и делаем не ссылку, а span (просто текстовый блок) -->
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <!-- Остальные кнопки отрисовываем без подсветки, со ссылками -->
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <!-- Если существует следующая страница 
           (если мы не на последней странице) 
           рисуем кнопку "Следующая"... -->
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Следующая
          </a>
        </li>
        <!-- ...и кнопку "Последняя" -->
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %} 

backend/templates/includes/scripts.html
{% load static %}
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

backend/templates/includes/user_card.html
{% load static %}
{% if user.cpus.count > 0 %}
  <div class="card mb-3 product-card" style="max-width: 540px;">
    <div class="row g-0">
      <div class="product-thumb card col-sm-4">
        {% if user.avatar %}
          <img src="{{ user.avatar.url }}" class="img-fluid rounded-start image-user-card"> 
        {% else %}
          <img src="{% static 'img/nouser.jpg' %}" class="img-fluid rounded-start image-user-card">
        {% endif %}
      </div>
      <div class="col-sm-8">
        <div class="card-body">
          <h5 class="card-title">{{ user.first_name }} {{ user.last_name }}</h5>
          <p class="card-text"><a href="{% url 'cpus:user_cpus' user.id %}"><span class="badge rounded-pill bg-primary text-bg-primary">@{{ user.username }}</span></a></p>
          <p class="card-text">
            <small class="text-body-secondary">Всего процессоров: <a href="{% url 'cpus:user_cpus' user.id %}">{{ user.cpus.count }}</a></small><br>
            <small class="text-body-secondary">
              Последнее добавление в коллекцию: {{ user.cpus.last.created_at|date:"SHORT_DATE_FORMAT" }}
            </small>
          </p>
          <a href="{% url 'cpus:user_cpus' user.id %}"><button type="button" class="btn btn-primary">Посмотреть коллекцию</button></a>
        </div>
      </div>
    </div>
  </div>
{% endif %}