backend/cpu_backend/urls.py
from django.contrib import admin
from django.views.generic.edit import CreateView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, reverse_lazy

from users.forms import CustomUserCreationForm

urlpatterns = [
    path('', include('cpus.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=CustomUserCreationForm,
            success_url=reverse_lazy('cpus:index'),
        ),
        name='registration',
    ),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Если проект запущен в режиме разработки
if settings.DEBUG:
    import debug_toolbar
    # Добавить к списку urlpatterns список адресов из приложения debug_toolbar:
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

handler404 = 'core.views.page_not_found'

backend/cpus/urls.py
from django.urls import path

from . import views

app_name = 'cpus'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'about/',
        views.About.as_view(),
        name='about'
    ),
    path('cpus_list/', views.cpus_list, name='cpus_list'),
    path('cpu_detail/<int:pk>/', views.cpu_detail, name='cpu_detail'),
    path('user_cpus/<int:pk>/', views.user_cpus, name='user_cpus'),
    path(
        'cpu_add/',
        views.CpuCreateView.as_view(),
        name='cpu_add'
    ),
    path(
        'cpu_detail/<int:pk>/edit/',
        views.CpuUpdateView.as_view(),
        name='cpu_edit',
    ),
    # path(
    #     'cpu_detail/<int:pk>/delete/',
    #     views.cpu_delete,
    #     name='cpu_delete'
    # ),
    path(
        'cpu_detail/<int:pk>/delete/',
        views.CpuDeleteView.as_view(),
        name='cpu_delete'
    ),
]

backend/cpus/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse

from cpu_backend.constants import (
    NAME_SHORT_NUMBCHAR,
    CHOICE_NUMBCHAR,
)
from cpus.validators import real_date

User = get_user_model()


def user_cpu_directory_path(instance, filename):
    """
    Функция для генерации пути сохранения изображений процессоров.
    Файл будет загружен в MEDIA_ROOT/user_<id>/cpu_<id>/<filename>
    """
    return 'user_{0}/cpu_{1}/{2}'.format(
        instance.cpu.user.id,
        instance.cpu.id,
        filename
    )


class BaseModel(models.Model):
    created_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name='Дата добавления',
    )

    class Meta:
        abstract = True


class Manufacturer(BaseModel):
    """
    Производитель
    """
    name = models.CharField(
        max_length=NAME_SHORT_NUMBCHAR,
        verbose_name='тип',
    )

    class Meta:
        verbose_name = 'производитель'
        verbose_name_plural = 'Производители'

    def __str__(self):
        return self.name


class Cpu(BaseModel):
    """
    Процессор
    """
    NOTEST = 'NT'
    WORK = 'WK'
    DEFECTIVE = 'DF'
    OVERCLOCK = 'OC'
    NONE = 'NN'
    COMMON = 'CM'
    UNOCOMMON = 'UN'
    RARE = 'RR'
    EXTRARARE = 'ER'

    RARITY_CHOICES = [
        (NONE, 'Не задано'),
        (COMMON, 'Частый'),
        (UNOCOMMON, 'Нечастый'),
        (RARE, 'Редкий'),
        (EXTRARARE, 'Очень редкий'),
    ]

    STATUS_CHOICES = [
        (NOTEST, 'Непроверенный'),
        (WORK, 'Рабочий'),
        (DEFECTIVE, 'Неисправен'),
        (OVERCLOCK, 'Разогнан'),
    ]

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='cpus',
        verbose_name='владелец'
    )
    part_number = models.CharField(
        max_length=NAME_SHORT_NUMBCHAR,
        verbose_name='серийный номер',
    )
    catalog_number = models.CharField(
        max_length=4,
        verbose_name='номер в коллекции',
        blank=True
    )

    description = models.TextField(
        blank=True,
        null=True,
        verbose_name='описание'
    )
    hidden_description = models.TextField(
        blank=True,
        null=True,
        verbose_name='Скрытое описание'
    )
    work_status = models.CharField(
        max_length=CHOICE_NUMBCHAR,
        choices=STATUS_CHOICES,
        default=NOTEST,
        verbose_name='статус'
    )
    rarity = models.CharField(
        max_length=CHOICE_NUMBCHAR,
        choices=RARITY_CHOICES,
        default=NONE,
        verbose_name='редкость'
    )
    manufacturer = models.ForeignKey(
        Manufacturer,
        on_delete=models.CASCADE,
        related_name='cpus',
        verbose_name='производитель',
    )
    family = models.CharField(
        max_length=NAME_SHORT_NUMBCHAR,
        verbose_name='семейство',
    )
    frequency = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='частота процессора',
    )
    fsb = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='частота шины',
        blank=True,
        null=True,
    )
    multiplier = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='множитель',
        blank=True,
        null=True,
    )
    fpu = models.BooleanField(
        default=True,
        verbose_name='математический сопроцессор (FPU)'
    )
    l1_cache_size = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='размер кеша L1',
        blank=True,
        null=True,
    )
    vcore = models.FloatField(
        validators=[MinValueValidator(1)],
        verbose_name='напряжение ядра',
        blank=True,
        null=True,
    )

    overclk_frequency = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='частота в разгоне',
        blank=True,
        null=True,
    )
    overclk_fsb = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='частота шины в разгоне',
        blank=True,
        null=True,
    )
    overclk_multiplier = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='множитель в разгоне',
        blank=True,
        null=True,
    )
    overclk_vcore = models.FloatField(
        validators=[MinValueValidator(1)],
        verbose_name='напряжение ядра в разгоне',
        blank=True,
        null=True,
    )

    purchase_date = models.DateField(
        verbose_name='дата покупки',
        validators=(real_date,)
    )
    purchase_price = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='стоимость покупки',
        blank=True,
        null=True,
    )
    sale_price = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='стоимость продажи',
        blank=True,
        null=True,
    )
    sale_date = models.DateField(
        verbose_name='дата продажи',
        blank=True,
        null=True,
        validators=(real_date,)
    )

    is_published = models.BooleanField(
        default=True,
        verbose_name='опубликовано',
        help_text='Снимите галочку, чтобы скрыть публикацию.'
    )
    in_interesting = models.BooleanField(
        default=False,
        verbose_name='В интересном',
        help_text='Снимите галочку, чтобы скрыть с главной.'
    )

    class Meta:
        ordering = ('-purchase_date', '-created_at')
        verbose_name = 'процессор'
        verbose_name_plural = 'Процессоры'
        constraints = (
            models.UniqueConstraint(
                fields=(
                    'catalog_number',
                    'user'
                ),
                name='uniq_cpu'
            ),
        )

    def __str__(self):
        return self.part_number

    def get_absolute_url(self):
        return reverse('cpus:cpu_detail', kwargs={'pk': self.pk})


class ImageCpu(models.Model):
    """
    Изображения для процессора
    """
    name = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        verbose_name='название изображения',
    )
    cpu = models.ForeignKey(
        Cpu,
        on_delete=models.CASCADE,
        related_name='images',
        verbose_name='процессор',
    )
    image = models.ImageField(
        upload_to=user_cpu_directory_path,
        verbose_name='фото процессора',
    )
    default = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        # Проверяем, есть ли уже у этого процессора изображение с default=True
        existing_default_image = ImageCpu.objects.filter(
            cpu=self.cpu,
            default=True
        ).first()
        if existing_default_image and self.default:
            # Если такое изображение существует и default=True,
            # то сбрасываем default на False у существующего изображения
            existing_default_image.default = False
            existing_default_image.save()
        super().save(*args, **kwargs)

backend/cpus/views.py
import datetime

from django.core.mail import send_mail
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
# from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count, Prefetch
from django.utils.timezone import make_aware
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView
)
from django.shortcuts import get_object_or_404, render
# from django.shortcuts import redirect

from cpus.models import Cpu, ImageCpu, User
from cpus.forms import CpuForm, ImageCpuFormSet
from carousel.models import Carousel
from cpu_backend.constants import (
    DAYS_INTERVAL,
)


def suffiks(obj_count):
    """Подстановка суффиксов согласно числу"""
    if obj_count == 1:
        suff = ''
    elif 1 < obj_count < 5:
        suff = 'а'
    else:
        suff = 'ов'
    return suff


def interval_cpus(days):
    """
    Вычисление даты интервала
    и соответствующие ей добавленных процессоров
    """
    today = datetime.datetime.today()
    aware_today = make_aware(today)  # Присваиваем тайм зону
    interval_date = aware_today - datetime.timedelta(days=days)
    interval_cpus = Cpu.objects.filter(
        created_at__range=(interval_date, aware_today)
    )
    return [interval_cpus, interval_date]


def index(request):
    banners = Carousel.objects.all()
    users = User.objects.all()
    users_list = users.annotate(
        cpu_count=Count('cpus')
    ).order_by(
        '-cpu_count', '-registrated_at'
    )[0:3]
    cpu_count = Cpu.objects.count()
    cpu_count_suff = suffiks(cpu_count)
    user_count_suff = suffiks(users.count())
    all_cpus = Cpu.objects.all()
    month_cpus = interval_cpus(DAYS_INTERVAL)[0]
    interest_cpus = Cpu.objects.filter(
        in_interesting=True
    )

    context = {
        'cpu_count_suff': cpu_count_suff,
        'user_count_suff': user_count_suff,
        'banners': banners,
        'users': users,
        'users_list': users_list,
        'all_cpus': all_cpus,
        'month_cpus': month_cpus,
        'interest_cpus': interest_cpus,
        'days_interval': DAYS_INTERVAL,
    }

    template_name = 'cpus/index.html'
    return render(request, template_name, context)


def cpus_list(request):
    month_cpus = interval_cpus(DAYS_INTERVAL)[0]

    # Получаем все процессоры с выбранными полями и связанными изображениями
    cpus_list = Cpu.objects.all().prefetch_related(
        Prefetch(
            'images',
            queryset=ImageCpu.objects.filter(default=True),
            to_attr='default_image'
        )
    )
    paginator = Paginator(cpus_list, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    for cpu in page_obj:
        if cpu in month_cpus:
            cpu.month_cpus = True

    context = {
        'page_obj': page_obj,
    }

    template_name = 'cpus/cpus_list.html'
    return render(request, template_name, context)


def cpu_detail(request, pk):
    interval_date = interval_cpus(DAYS_INTERVAL)[1]

    cpu = get_object_or_404(
        Cpu,
        id=pk,
    )
    cpu_images = ImageCpu.objects.filter(
        cpu__id=pk
    )

    if cpu.created_at >= interval_date:
        cpu.month_cpus = True

    context = {
        'cpu': cpu,
        'cpu_images': cpu_images,
    }

    template_name = 'cpus/cpu_detail.html'
    return render(request, template_name, context)


def user_cpus(request, pk):
    today = datetime.datetime.today()
    aware_today = make_aware(today)  # Присваиваем тайм зону
    month = aware_today - datetime.timedelta(days=3)
    month_cpus = Cpu.objects.filter(
        created_at__range=(month, aware_today)
    )

    user = User.objects.get(id=pk)
    cpus_list = Cpu.objects.filter(
        user=user.id
    ).prefetch_related(
        Prefetch(
            'images',
            queryset=ImageCpu.objects.filter(default=True),
            to_attr='default_image'
        )
    )
    for cpu in cpus_list:
        if cpu in month_cpus:
            cpu.month_cpus = True

    context = {
        'user': user,
        'cpus_list': cpus_list,
    }

    template_name = 'cpus/user_cpus.html'
    return render(request, template_name, context)


class About(TemplateView):
    """
    Вью для страницы «О проекте»
    """
    template_name = 'cpus/about.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['banners'] = Carousel.objects.all()
        return data


class CpuCreateView(LoginRequiredMixin, CreateView):
    """
    Вью для создания процессора
    """
    model = Cpu
    form_class = CpuForm
    template_name = 'cpus/cpu_add_edit.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['image_formset'] = ImageCpuFormSet(
                self.request.POST,
                self.request.FILES
            )
        else:
            data['image_formset'] = ImageCpuFormSet()
        return data

    def form_valid(self, form):
        form.instance.user = self.request.user

        context = self.get_context_data()
        image_formset = context['image_formset']

        if image_formset.is_valid():
            self.object = form.save()
            image_formset.instance = self.object
            image_formset.save()

            # Отправка письма после успешного сохранения формы и формсета
            part_number = self.object.part_number
            user = self.object.user
            send_mail(
                subject='Добавление процессора на сайт 486.renzhin.ru',
                message=f'{user} добавил процессор {part_number}',
                from_email='noreplay@486.renzhin.ru',
                recipient_list=['admin@486.renzhin.ru'],
                fail_silently=True,
            )

            return super().form_valid(form)

        else:
            return self.form_invalid(form)


class CpuUpdateView(LoginRequiredMixin, UpdateView):
    """
    Вью для редактирования процессора
    """
    model = Cpu
    form_class = CpuForm
    template_name = 'cpus/cpu_add_edit.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['image_formset'] = ImageCpuFormSet(
                self.request.POST,
                self.request.FILES,
                instance=self.object
            )
        else:
            data['image_formset'] = ImageCpuFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        image_formset = context['image_formset']
        if image_formset.is_valid():
            self.object = form.save()
            image_formset.instance = self.object
            image_formset.save()
            return super().form_valid(form)
        else:
            return self.form_invalid(form)

    def dispatch(self, request, *args, **kwargs):
        instance = get_object_or_404(Cpu, pk=kwargs['pk'])
        if instance.user != request.user:
            # Здесь вызов ошибки, или редирект на нужную страницу.
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class CpuDeleteView(LoginRequiredMixin, DeleteView):
    """
    Вью для удаления процессора
    """
    model = Cpu
    template_name = 'cpus/cpu_add_edit.html'
    success_url = reverse_lazy('cpus:index')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['cpu_images'] = data['cpu'].images.filter(default=True).first()
        return data

    def dispatch(self, request, *args, **kwargs):
        instance = get_object_or_404(Cpu, pk=kwargs['pk'])
        if instance.user != request.user:
            # Здесь вызов ошибки, или редирект на нужную страницу.
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

backend/templates/cpus/about.html
<!-- about.html --> 
{% extends "base.html" %}
{% block title %}Коллекция 486. О проекте.{% endblock %}
{% block content %}
<section class="main-content">
  <div class="container">
    <h1>О проекте</h1>
    <p class="about-text">
      Проект создан коллекционером 486 процессоров и, по совместительству, разработчиком на языке Python / фреймворк Django.
    <br>
      По сути, сайт является отправной точкой для дальнейшего создания полномасштабного проекта для коллекционеров различного компьютерного железа. Объять все и сразу в одиночку довольно сложно, поэтому я начал с малого — закрыл потребность в каталогизации экземпляров собственной коллекции.
    </p>
    <p class="about-text">Замечания и предложения направляйте в телеграм @renzhin</p>
  </div>
</section>
{% endblock %}

backend/templates/cpus/cpu_add.html
<!-- cpu_add.html --> 
{% extends "base.html" %}
{% block title %}Коллекция 486. Добавить процессор.{% endblock %}
{% block content %}
<section class="main-content">
  <div class="container">
    <h1>О проекте</h1>
    <form method="post"> 
      {% csrf_token %}
      <table>
       {{ form }}
      </table>
      <input type="submit" value="Отправить">
    </form>
    {% with data=form.instance %}
      {% if form.is_valid %}
        <p>ID новой записи в БД: {{ data.id }}</p>
      {% endif %}
    {% endwith %}
  </div>
</section>
{% endblock %}

backend/templates/cpus/cpu_add_edit.html
<!-- cpu_add_edit.html --> 
{% extends "base.html" %}
{% block title %}
{% with data=form.instance %}
  {% if '/edit/' in request.path %}
    Коллекция 486. Изменить процессор {{ data.part_number }}.
  {% elif '/delete/' in request.path %}
    Коллекция 486. Удалить процессор {{ cpu.part_number }}.
  {% else %}
    Коллекция 486. Добавить процессор.
  {% endif %}
{% endwith %}
{% endblock %}
{% block content %}
{% with data=form.instance %}
  <section class="main-content">
    <div class="container">
      {% if '/edit/' in request.path %}
        <h1>Изменить процессор {{ data.part_number }}</h1>
      {% elif '/delete/' in request.path %}
        <h1>Удалить процессор {{ cpu.part_number }}</h1>
      {% else %}
        <h1>Добавить процессор</h1>
      {% endif %}
      
      <form method="post" enctype="multipart/form-data"> 
        {% csrf_token %}

        <table>
        {% if not "/delete/" in request.path %}

        {{ form.as_table }}
        {% if form.instance.pk %}
          <h4>Изображения процессора:</h4>
          {% for image in form.instance.images.all %}
            <img src="{{ image.image.url }}" class="mt-2 me-1 image-detail-gal" alt="Изображение процессора">
          {% endfor %}
        {% endif %}
        {{ image_formset.management_form }}
        {% for image_form in image_formset %}
          {{ image_form }}
        {% endfor %}

        {% else %}
          <p>Коллекционер: {{ cpu.user }}</p>
          {% if cpu_images %}
           <p><img src="{{ cpu_images.image.url }}" class="mt-2 me-1 image-detail-gal" alt="Процессор {{ cpu.part_number }}"></p>
          {% endif %}
        {% endif %}
        </table>

        <input type="submit" value="Отправить">
      </form>

      {% if form.is_valid %}
        <p>ID новой записи в БД: {{ data.part_number }}</p>
      {% endif %}
    </div>
  </section>
  {% endwith %}
{% endblock %}

backend/templates/cpus/cpu_detail.html
<!-- cpu_detail.html --> 
{% extends "base.html" %}
{% block title %}
  Процессор {{ cpu.part_number }}
  в коллекции {{ cpu.user.username }}
{% endblock %}
{% block content %}
  <!-- Страница процессора -->
  <section class="main-content">
    <div class="container">
      <div class="row">
        <div class="col-xl-6 col-md-7">

          <h2>{{ cpu.part_number }}</h2>
          {% if cpu.user == user %}
            <a href="{% url 'cpus:cpu_edit' cpu.id %}">Изменить процессор</a>
            <a href="{% url 'cpus:cpu_delete' cpu.id %}">Удалить процессор</a>
          {% endif %}
            <div class="cpu_badges">
              <span class="badge rounded-pill bg-danger text-bg-primary">
                {{ cpu.get_rarity_display }}
              </span>
              <span class="badge rounded-pill bg-success text-bg-primary">
                {{ cpu.get_work_status_display }}
              </span>
            </div>
          <table class="table table-sm">
            <tbody class="table-group-divider">
              <tr>
                <th scope="row">Производитель</th>
                <td>{{ cpu.manufacturer }}</td>
              </tr>
              <tr>
                <th scope="row">Семейство</th>
                <td>{{ cpu.family }}</td>
              </tr>
              <tr>
                <th scope="row">Частота</th>
                <td>{{ cpu.frequency }} Мгц</td>
              </tr>
              {% if cpu.fsb %}
              <tr>
                <th scope="row">Частота шины</th>
                <td>{{ cpu.fsb }} Мгц</td>
              </tr>
              {% endif %}
              {% if cpu.multiplier %}
              <tr>
                <th scope="row">Множитель</th>
                <td>{{ cpu.multiplier }}</td>
              </tr>
              {% endif %}
              <tr>
                <th scope="row">Сопроцессор</th>
                <td>{{ cpu.fpu|yesno:"Есть,Отсутствует" }}</td>
              </tr>
              {% if cpu.l1_cache_size %}
              <tr>
                <th scope="row">Кэш L1</th>
                <td>{{ cpu.l1_cache_size }} Кб</td>
              </tr>
              {% endif %}
              {% if cpu.vcore %}
              <tr>
                <th scope="row">Напряжение ядра</th>
                <td>{{ cpu.vcore }} В</td>
              </tr>
              {% endif %}
            </tbody>
          </table>
          <br>
          <h6 class="cpu_font_user">
            {% if cpu.month_cpus %}
              <span class="badge bg-secondary text-bg-secondary">Новый</span>
            {% endif %} 
            В коллекции {{ cpu.user.first_name }} {{ cpu.user.last_name }} </strong> <a href="{% url 'cpus:user_cpus' cpu.user.id %}"><span class="badge rounded-pill bg-primary text-bg-primary">@{{ cpu.user.username }}</span></a></h6>
          <ul class="list-group">
            <li class="list-group-item">Приобретен {{ cpu.purchase_date }} за {{ cpu.purchase_price }} руб.</li>
            <li class="list-group-item">Продан {{ cpu.purchase_date }} за {{ cpu.purchase_price }} руб.</li>
          </ul>

          <br>

          <table class="table table-sm">
            <tbody class="table-group-divider">
              {% if cpu.overclk_frequency %}
              <tr>
                <th scope="row">Частота в разгоне</th>
                <td>{{ cpu.overclk_frequency }} Мгц</td>
              </tr>
              {% endif %} 
              {% if cpu.overclk_fsb %}
              <tr>
                <th scope="row">Частота шины в разгоне</th>
                <td>{{ cpu.overclk_fsb }} Мгц</td>
              </tr>
              {% endif %}
              {% if cpu.overclk_multiplier %}
              <tr>
                <th scope="row">Множитель в разгоне</th>
                <td>{{ cpu.overclk_multiplier }}</td>
              </tr>
              {% endif %}
            </tbody>
          </table>
          {% if cpu.description %}
          <br>
          <p>
            {{ cpu.description }}
          </p>
          {% endif %}
        </div>
        
        <div class="col-xl-6 col-md-5">

          {% for image in cpu_images %}
            {% if image.default %}
              <!-- Выводим остальные изображения -->
              <!-- URL trigger modal -->
              <a href="" data-bs-toggle="modal" data-bs-target="#Modal{{ image.id }}">
                <img src="{{ image.image.url }}" alt="Процессор {{ cpu.part_number }}"></a>
              <!-- Modal -->
              <div class="modal fade" id="Modal{{ image.id }}" tabindex="-1" aria-labelledby="ModalLabel{{ image.id }}" aria-hidden="true">
                <div class="modal-dialog modal-lg modal-fullscreen-lg-down">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="ModalLabel{{ image.id }}">Процессор {{ cpu.part_number }}</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <img class="image-modal" style="max-width: 100%" src="{{ image.image.url }}" alt="Процессор {{ cpu.part_number }}">
                    </div>
                  </div>
                </div>
              </div>
            {% endif %}
          {% endfor %}


          {% for image in cpu_images %}
            {% if not image.default %}
              <!-- Выводим остальные изображения -->
              <!-- URL trigger modal -->
              <a href="" data-bs-toggle="modal" data-bs-target="#Modal{{ image.id }}">
                <img src="{{ image.image.url }}" class="mt-2 me-1 image-detail-gal" alt="Процессор {{ cpu.part_number }}"></a>
              <!-- Modal -->
              <div class="modal fade" id="Modal{{ image.id }}" tabindex="-1" aria-labelledby="ModalLabel{{ image.id }}" aria-hidden="true">
                <div class="modal-dialog modal-lg modal-fullscreen-lg-down">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="ModalLabel{{ image.id }}">Процессор {{ cpu.part_number }}</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <img class="image-modal" style="max-width: 100%" src="{{ image.image.url }}" alt="Процессор {{ cpu.part_number }}">
                    </div>
                  </div>
                </div>
              </div>
            {% endif %}
          {% endfor %}

        </div>
      </div>
    </div>
  </section>
{% endblock %}

backend/templates/cpus/index.html
<!-- index.html --> 
{% extends "base.html" %}
{% block title %}Коллекция 486. Главная страница.{% endblock %}
{% block content %}
  <!-- Страница Главная-->
  <section class="main-content">
    <div class="container">
      <div class="row">
        <div class="col-xl-6 col-md-7">
          <h3>Топ-3 коллекционеров</h3>
          {% for user in users_list %}
            {% include "includes/user_card.html" %}
          {% endfor %}
        </div>
        <div class="col-xl-6 col-md-5">

          <h4>Всего на проекте</h4>
          <ul class="list-unstyled">
            <li>{{ users.count }} коллекционер{{ user_count_suff }}</li>
            <li><a href="{% url 'cpus:cpus_list' %}">{{ all_cpus.count }} процессор{{ cpu_count_suff }}</a></li>
          </ul>

          <h4>CPU за последние {{ days_interval }} дней <span class="badge bg-secondary text-bg-secondary">Новый</span></h4>
          <ul class="list-unstyled">
            {% for cpu in month_cpus %}
              <!-- Карточка -->
              {% include "includes/mini_cpu.html" %}  
            {% endfor %}
          </ul>

          <h4>Интересные экземпляры</h4>
          <ul class="list-unstyled">
            {% for cpu in interest_cpus %}
              <!-- Карточка -->
              {% include "includes/mini_cpu.html" %}  
            {% endfor %}
          </ul>

        </div> 
      </div>
    </div>
  </section>
{% endblock %}